name: ingress-nginx-builder

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/lkinderbueno/ingress-nginx
          VERSION=v1.10
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          BASE_IMAGE=ghcr.io/lkinderbueno/nginx:v0.0.5
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=branch::${BRANCH}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: go version
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
           chmod +x ./build/build.sh
           ./build/build.sh
        shell: bash
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./rootfs
          file: ./rootfs/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            "BASE_IMAGE=${{BASE_IMAGE}}"
            "VERSION=${{ VERSION }}"
          #cache-from: type=registry,ref=ghcr.io/lkinderbueno/nginx:buildcache
          #cache-to: type=registry,ref=ghcr.io/lkinderbueno/nginx:buildcache,mode=max